# Усложненный make-file. Введены переменные для параметров компиляции и исполняемых файлов

.PHONY: все отладочные версии чистые

RELEASE_FLAGS = -O2 -Wall -DNDEBUG
DEBUG_FLAGS = -g -O0 -Wall
RELEASE_EXEC = Kazino-Royal
DEBUG_EXEC = Kazino-Royal-dbg
ИСТОЧНИК = Kazino-Royal.cpp

все: debug release

debug: $(DEBUG_EXEC)

Kazino-Royal-dbg: $(ИСТОЧНИК)
 g++ $(DEBUG_FLAGS) $(SOURCE) -o $(DEBUG_EXEC) 

релиз: $(RELEASE_EXEC)

Kazino-Royal: $(ИСТОЧНИК)
 g++ $(RELEASE_FLAGS) $(SOURCE) -o $(RELEASE_EXEC)

чистый:
 rm -f $(RELEASE_EXEC) $(DEBUG_EXEC)